### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by mibu138** [wetadigital/USDPluginExamples#10]
### Description of Issue
All tests fail after a fresh build.
### Steps to Reproduce
1. After building, from the build directory, I run:
```
michaelb@boswell:~/dev/USDPluginExamples/build$ /usr/local/bin/ctest --force-new-ctest-process --output-on-failure
Test project /home/michaelb/dev/USDPluginExamples/build
    Start 1: usdTri_testTriangle
1/2 Test #1: usdTri_testTriangle ...............***Failed    0.03 sec
Traceback (most recent call last):
  File "/home/michaelb/dev/USDPluginExamples/src/usdTri/tests/testTriangle.py", line 2, in <module>
    from pxr import Gf, Vt, Usd, UsdGeom
  File "/home/michaelb/dev/USD/build/lib/python/pxr/Gf/__init__.py", line 31, in <module>
    from pxr import Tf
  File "/home/michaelb/dev/USD/build/lib/python/pxr/Tf/__init__.py", line 85, in <module>
    from . import _tf
ImportError: dynamic module does not define init function (init_tf)

    Start 2: usdTriFileFormat_testFileFormat
2/2 Test #2: usdTriFileFormat_testFileFormat ...***Failed    0.02 sec
Traceback (most recent call last):
  File "/home/michaelb/dev/USDPluginExamples/src/usdTriFileFormat/tests/testFileFormat.py", line 3, in <module>
    from pxr import Vt, Gf, Sdf, Usd, UsdGeom
  File "/home/michaelb/dev/USD/build/lib/python/pxr/Vt/__init__.py", line 31, in <module>
    from . import _vt
ImportError: dynamic module does not define init function (init_vt)


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.06 sec

The following tests FAILED:
	  1 - usdTri_testTriangle (Failed)
	  2 - usdTriFileFormat_testFileFormat (Failed)
Errors while running CTest
```

### System Information (OS, Hardware)
Linux OS. Ubuntu 19.10. Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz.  GeForce RTX 2080 Driver Version: 450.56.11
### Build Flags
Built with the following commands. $USD=/path/to/usd/build/root
```
michaelb@boswell:~/dev/USDPluginExamples/build$ cmake -DUSD_ROOT=$USD -DTBB_ROOT=$USD -DBOOST_ROOT=$USD -DBUILD_TESTING=ON ..
michaelb@boswell:~/dev/USDPluginExamples/build$ cmake --build  . -- VERBOSE=1 -j8 all test install
```

**Comment by rlei-weta** [comment]
Hi @mokchira - thanks for the report!

I'm suspecting that the runtime python version (running the tests) is incompatible with the python library version that your USD installation built against.

May you please attach CMakeCache.txt files from _both_ the USD installation _and_ USDPluginExamples installation?

Btw - did you also see test failure when after executing the following:
```
cmake --build  . -- VERBOSE=1 -j8 all test install
```
The "test" target should have ideally triggered ctest.

**Comment by mibu138** [comment]
Sure thing! 

I built USD with Python 3.7.5. I don't have a CMakeCache.txt in my USD install dir because I built it using the build_usd.py script, but I can include $USD_ROOT/cmake/pxrTargets.cmake which lists the python libraries used to build.

The USDPluginExamples CMakeCache.txt:
[CMakeCache.txt](https://github.com/wetadigital/USDPluginExamples/files/5633114/CMakeCache.txt)

pxrTargets.cmake:
[pxrTargets.cmake.txt](https://github.com/wetadigital/USDPluginExamples/files/5633142/pxrTargets.cmake.txt)
 (i included the .txt so the uploader wouldn't complain)

And yes, the tests fail on that build command as well.

**Comment by rlei-weta** [comment]
Hi @mokchira - thanks for the attachments - will look at these later tonight!

If you built with `build_usd.py`, the `CMakeCache.txt` of USD should reside under:
```
<USD_INSTALL_ROOT>/build/USD/
```

**Comment by mibu138** [comment]
Ah yes, there it is. Thanks for that.
Here it is:
[CMakeCache.txt](https://github.com/wetadigital/USDPluginExamples/files/5633179/CMakeCache.txt)

**Comment by rlei-weta** [comment]
Ah - had a quick peak at USDPluginExample's CMakeCache.txt

What happens if you pass:
```
-DUSE_PYTHON_3=ON
```

During cmake configuration?

**Comment by mibu138** [comment]
Yup, that was it! Thanks!

**Comment by rlei-weta** [comment]
Great, @mokchira - lemmi know if you find anything else!
