### ISSUE TITLE
Sample triangle (triangle.usda) is not rendered in the usdview on MacOS.

### ISSUE THREAD

**Issue by czech-j** [wetadigital/USDPluginExamples#33]
### Description of Issue

I managed to build everything on MacOS with official Pixar USD (as well as with our custom version), but the problem is the same - when I run usdview with your example (triangle.usda) I have a console bug from usdview like below (see also Steps to Reproduce) and the triangle is not really rendered (is not visible).  However, all properties (names, values) of the triangle schema (like doubleSided, extend, orientation etc.) are visible and displayed correctly in usdview. It looks like the schema itself is being loaded into usbview, there is a rendering problem.

![triangle-example-in-usd](https://user-images.githubusercontent.com/11073323/131480408-90de78dc-dbd5-4ac6-88c1-a0263946770b.png)

![usdview-error-with-triangle](https://user-images.githubusercontent.com/11073323/131663348-83b51bf9-96b1-440c-90cd-779ef3b97337.png)

Seems like  usdTriImaging.dylib is expected in /Users/lb/Projects/USDPluginExamples/install/plugin folder. But the  usdTriImaging.dylib  has not been generated/installed. Instead of this file another one was generated/installed -  usdTriImaging.so. See my project folders:

![project-folders](https://user-images.githubusercontent.com/11073323/131667773-890e3e2c-90cf-4ddf-af9b-e120cbd56c1f.png)

Standard USD prims like cube or sphere and others render seamlessly.

![cube-in-usd](https://user-images.githubusercontent.com/11073323/131503654-3577dbe3-ed15-4d7a-8fbd-d7a322f6b1e2.png)

### System Information (OS, Hardware)

macOS BigSure 11.4 (Intel Core i7)

### Steps to Reproduce

1. run usdview triangle.usda

Error:
ERROR: Usdview encountered an error while rendering.
Error in 'pxrInternal_v0_21__pxrReserved__::PlugPlugin::Load' at line 258 in file /Users/lb/Projects/usd-metal/usd-metal/pxr/base/plug/plugin.cpp : 'Failed to load plugin 'usdTriImaging': dlopen(/Users/lb/Projects/USDPluginExamples/install/plugin/usdTriImaging.dylib, 2): image not found in '/Users/lb/Projects/USDPluginExamples/install/plugin/usdTriImaging.dylib''
Error in 'pxrInternal_v0_21__pxrReserved_::UsdImagingAdapterRegistry::ConstructAdapter' at line 171 in file /Users/lb/Projects/usd-metal/usd-metal/pxr/usdImaging/usdImaging/adapterRegistry.cpp : '[PluginLoad] PlugPlugin could not be loaded for TfType 'UsdTriImagingTriangleAdapter'

### Build Flags

 cmake \                                
  -DUSD_ROOT="/Users/lb/Projects/usd-metal/Builds/USD/" \
  -DTBB_ROOT="/Users/lb/Projects/usd-metal/Builds/USD" \
  -DBOOST_ROOT="/Users/lb/Projects/usd-metal/Builds/USD" \
  -DBUILD_TESTING=ON \
  -DCMAKE_INSTALL_PREFIX="/Users/lb/Projects/USDPluginExamples/install/" \
  ..

cmake --build  . -- VERBOSE=1 -j8 install

**Comment by n-burk** [comment]
I have the same issue on Windows 11
USD version 0.22.3 & 21.05

**Comment by rlei-weta** [comment]
Apologies, this completely fell off our radar and we'll look at this soon.

**Comment by rlei-weta** [comment]
Hey @n-burk - may you describe your issue on Windows in more detail?  Are you not seeing a triangle rendered?  What does the installation of USDPluginExamples look like (are the library files suffixed with .so like in the original issue description)?

**Comment by rlei-weta** [comment]
@czech-j sorry for taking so long to get to this.  MacOS is not tried & supported at the moment -- however I have access to one now and will start looking at this!

**Comment by n-burk** [comment]
Sorry for the late reply but I got it working with a debug build. I think it's something with my own setup I'll need to track down

![image](https://user-images.githubusercontent.com/83418742/169949730-6344e29c-8492-4214-89b2-bcd85a9fac51.png)

> Hey @n-burk - may you describe your issue on Windows in more detail? Are you not seeing a triangle rendered? What does the installation of USDPluginExamples look like (are the library files suffixed with .so like in the original issue description)?
