### ISSUE TITLE
Build against MayaUSD 0.16

### ISSUE THREAD

**Issue by olihey** [wetadigital/USDPluginExamples#36]
### Description of Issue

I am trying to get the example plugins build with the pre-built USD 21.11 that comes with MayaUSD 0.16.
Any pointer would be helpful

### Steps to Reproduce
1. Install MayaUSD 0.16 for Maya 2022
2. Get the repo
3. `mkdir build`
4. `cd build`
5. `cmake .. -G "Visual Studio 16 2019" -DUSE_PYTHON_3=ON -DUSD_ROOT="C:\Program Files\Autodesk\MayaUSD\Maya2022\0.16.0_202202052333-1c49ce6\mayausd\USD3" -DTBB_ROOT="C:\Program Files\Autodesk\MayaUSD\Maya2022\0.16.0_202202052333-1c49ce6\mayausd\USD3" -DBOOST_ROOT="C:\Program Files\Autodesk\MayaUSD\Maya2022\0.16.0_202202052333-1c49ce6\mayausd\USD3"`

```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19044.
-- The CXX compiler identification is MSVC 19.29.30145.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Program Files/Python37/python.exe (found suitable version "3.7.7", minimum required is "3.0")
-- Found PythonLibs: C:/Program Files/Python37/libs/python37.lib (found suitable version "3.7.7", minimum required is "3.0")
-- Found Boost 1.70.0 at C:/Program Files/Autodesk/MayaUSD/Maya2022/0.16.0_202202052333-1c49ce6/mayausd/USD3/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED
-- Found boost_headers 1.70.0 at C:/Program Files/Autodesk/MayaUSD/Maya2022/0.16.0_202202052333-1c49ce6/mayausd/USD3/lib/cmake/boost_headers-1.70.0
-- Found Boost: C:/Program Files/Autodesk/MayaUSD/Maya2022/0.16.0_202202052333-1c49ce6/mayausd/USD3/lib/cmake/Boost-1.70.0/BoostConfig.cmake (found version "1.70.0")
-- Disabling boost-provided cmake config
-- Found Boost: C:/Program Files/Autodesk/MayaUSD/Maya2022/0.16.0_202202052333-1c49ce6/mayausd/USD3/include/boost-1_70 (found version "1.70.0") found components: python37
-- Found TBB: C:/Program Files/Autodesk/MayaUSD/Maya2022/0.16.0_202202052333-1c49ce6/mayausd/USD3/include (found version "2020.2")
-- Configuring done
CMake Error in src/usdTri/CMakeLists.txt:
  Imported target "js" includes non-existent path

    "/include/boost-1_70"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

The error keeps repeating several dozen times

### System Information (OS, Hardware)

Windows 10 Enterprise, Visual Studio 2019, CMake 3.20, Autodesk Naya 2022 & MayaUSD 0.16 for Maya 2022

### Build Flags

Nothing special

**Comment by rlei-weta** [comment]
@olihey, apologies for the late response.

Could you try cmake configuring with an additional definition:
```cmake
-DPXR_USD_LOCATION="C:\Program Files\Autodesk\MayaUSD\Maya2022\0.16.0_202202052333-1c49ce6\mayausd\USD3"
```

And see if that helps?  

I was able to reproduce a similar issue and noticed that the cmake/pxrTargets.cmake (`C:\Program Files\Autodesk\MayaUSD\Maya2022\0.16.0_202202052333-1c49ce6\mayausd\USD3\cmake\pxrTargets.cmake`) shipped with pre-built Maya USDs use ${PXR_USD_LOCATION} as the USD root prefix when defining the interface properties for imported libraries (such as js).

**Comment by olihey** [comment]
@rlei-weta Yep, that did the trick. Thanks
