### ISSUE TITLE
Build instructions not setting up the necesary include and library paths for install

### ISSUE THREAD

**Issue by mibu138** [wetadigital/USDPluginExamples#8]
Hi all. Love the project but hit a stumble on installation. 
Im on linux. I cloned USD from github so the USD include dir and USD library dir live in $HOME/dev/USD/build and are not on any default search paths.
Following the build instructions I pass my USD_ROOT to cmake and it generates the Makefile fine. 
However, when I run 
`cmake --build  . -- VERBOSE=1 -j8 all test install`
or when i run
`make`
I get compiler errors complaining that it cant find the USD header files.
So I can fix that by setting the env variable CPLUS_INCLUDE_PATH to the usd include dir.
Then I get linking errors though. Which I can fix by setting LIBRARY_PATH to the usd library dir.
I'm not familiar with how cmake works at all really, but since I provide it with my the root of my USD build, and I can see in CMakeCache.txt that it does correctly have the USD_INCLUDE_DIR and USD_LIBRARY_DIR set, shouldn't it also be able to set these up to be used by the Makefile for building?

**Comment by rlei-weta** [comment]
Hi @mokchira!

After you cloned USD locally, did you install it using the `./build_scripts/build_usd.py` script or manually via cmake?

The `USD_ROOT` option passed in to configure USDPluginExamples should be the root directory of the USD _installation_.  

For example, if you built USD with the `./build_scripts/build_usd.py` in your local clone:
```bash
python ./build_scripts/build_usd.py /path/to/usd/installation
```
... when configuring USDPluginExamples, the `USD_ROOT` should be `/path/to/usd/installation`.  And in fact, if you install USD using `build_usd.py`, all its dependencies are installed along with it.  So `TBB_ROOT` and `BOOST_ROOT` can also point to `/path/to/usd/installation`.  

Using the `build_usd.py` helper script would be my recommendation if it is your first time building/installing USD.

If you installed USD _manually_ via cmake, the `CMAKE_INSTALL_PREFIX` option would have specified the USD installation root. And if `CMAKE_INSTALL_PREFIX` was unspecified, USD would have been installed into `/usr/local`.

Let us know how you go, and if you run into any other issues building and installing.  Thanks for checking in :-)

**Comment by mibu138** [comment]
Hi, thanks for the swift reply.
I did use the build_usd.py script to build USD locally. Basically my USD project structure looks like this:
~/dev/USD          <--- the clone from https://github.com/PixarAnimationStudios/USD
~/dev/USD/build <--- the path to my USD installation (the argument to build_usd.py)
And ~/dev/USD/build is what I set USD_ROOT to when configuring USDPluginExamples. 
I did not actually set TBB_ROOT or BOOST_ROOT however, because I have them installed system-wide and cmake was able to find them. But this turns out to have been the issue it seems. I did you suggested above and I set both TBB_ROOT and BOOST_ROOT to ~/dev/USD/build and then had no compilation or linking errors.
All those linking and compilation errors came from not being able to find the USD library and headers though, not the boost or tbb ones, so I don't understand why setting the BOOST_ROOT and TBB_ROOT to the usd install path fixed it. 
I'm not sure what I would do if I did actually want to use the system boost or tbb, so there still seems to be some kind of issue here.

**Comment by mibu138** [comment]
Just to be clear these are the commands I was running originally and the compilation error:
```
michaelb@boswell:~/dev/USDPluginExamples/build$ rm -r *
michaelb@boswell:~/dev/USDPluginExamples/build$ ls .
michaelb@boswell:~/dev/USDPluginExamples/build$ ls ..
build  cmake  CMakeLists.txt  images  LICENSE  README.md  src
michaelb@boswell:~/dev/USDPluginExamples/build$ echo $USD
/home/michaelb/dev/USD/build
michaelb@boswell:~/dev/USDPluginExamples/build$ cmake -DUSD_ROOT=$USD .. 
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2.7") 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.17", minimum required is "2.7") 
-- Found Boost: /usr/include (found version "1.67.0")  
-- Found Boost: /usr/include (found version "1.67.0") found components: python27 
-- /home/michaelb/dev/USD/build
-- Found USD: /home/michaelb/dev/USD/build/include (found version "0.20.11") 
-- Found TBB: /usr/include (found version "2019.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/michaelb/dev/USDPluginExamples/build
michaelb@boswell:~/dev/USDPluginExamples/build$ make
Scanning dependencies of target usdTri
[  4%] Building CXX object src/usdTri/CMakeFiles/usdTri.dir/tokens.cpp.o
In file included from /home/michaelb/dev/USDPluginExamples/src/usdTri/tokens.cpp:6:
/home/michaelb/dev/USDPluginExamples/src/usdTri/./tokens.h:18:10: fatal error: pxr/pxr.h: No such file or directory
   18 | #include "pxr/pxr.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/usdTri/CMakeFiles/usdTri.dir/build.make:83: src/usdTri/CMakeFiles/usdTri.dir/tokens.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:224: src/usdTri/CMakeFiles/usdTri.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Changing that cmake line to 
`cmake -DUSD_ROOT=$USD -DTBB_ROOT=$USD -DBOOST_ROOT=$USD .`
allows the make command to run successfully.

**Comment by rlei-weta** [comment]
Hi @mokchira - interesting... will have a try to reproduce it later tonight.

In the meanwhile, can you run `make VERBOSE=1` and paste the output after configuring with only the USD_ROOT option `cmake -DUSD_ROOT=$USD ..`.  Interested in seeing what the actual compiler command & flags are!

**Comment by mibu138** [comment]
Sure thing! 
```
michaelb@boswell:~/dev/USDPluginExamples/build$ make VERBOSE=1
/usr/local/bin/cmake -S/home/michaelb/dev/USDPluginExamples -B/home/michaelb/dev/USDPluginExamples/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/michaelb/dev/USDPluginExamples/build/CMakeFiles /home/michaelb/dev/USDPluginExamples/build/CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/michaelb/dev/USDPluginExamples/build'
make  -f src/usdTri/CMakeFiles/usdTri.dir/build.make src/usdTri/CMakeFiles/usdTri.dir/depend
make[2]: Entering directory '/home/michaelb/dev/USDPluginExamples/build'
cd /home/michaelb/dev/USDPluginExamples/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /home/michaelb/dev/USDPluginExamples /home/michaelb/dev/USDPluginExamples/src/usdTri /home/michaelb/dev/USDPluginExamples/build /home/michaelb/dev/USDPluginExamples/build/src/usdTri /home/michaelb/dev/USDPluginExamples/build/src/usdTri/CMakeFiles/usdTri.dir/DependInfo.cmake --color=
Dependee "/home/michaelb/dev/USDPluginExamples/build/src/usdTri/CMakeFiles/usdTri.dir/DependInfo.cmake" is newer than depender "/home/michaelb/dev/USDPluginExamples/build/src/usdTri/CMakeFiles/usdTri.dir/depend.internal".
Dependee "/home/michaelb/dev/USDPluginExamples/build/src/usdTri/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/michaelb/dev/USDPluginExamples/build/src/usdTri/CMakeFiles/usdTri.dir/depend.internal".
Scanning dependencies of target usdTri
make[2]: Leaving directory '/home/michaelb/dev/USDPluginExamples/build'
make  -f src/usdTri/CMakeFiles/usdTri.dir/build.make src/usdTri/CMakeFiles/usdTri.dir/build
make[2]: Entering directory '/home/michaelb/dev/USDPluginExamples/build'
[  4%] Building CXX object src/usdTri/CMakeFiles/usdTri.dir/tokens.cpp.o
cd /home/michaelb/dev/USDPluginExamples/build/src/usdTri && /usr/bin/c++  -DusdTri_EXPORTS -I/home/michaelb/dev/USDPluginExamples/build/include -isystem /usr/include/python2.7  -O3 -DNDEBUG -fPIC   -o CMakeFiles/usdTri.dir/tokens.cpp.o -c /home/michaelb/dev/USDPluginExamples/src/usdTri/tokens.cpp
In file included from /home/michaelb/dev/USDPluginExamples/src/usdTri/tokens.cpp:6:
/home/michaelb/dev/USDPluginExamples/src/usdTri/./tokens.h:18:10: fatal error: pxr/pxr.h: No such file or directory
   18 | #include "pxr/pxr.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/usdTri/CMakeFiles/usdTri.dir/build.make:83: src/usdTri/CMakeFiles/usdTri.dir/tokens.cpp.o] Error 1
make[2]: Leaving directory '/home/michaelb/dev/USDPluginExamples/build'
make[1]: *** [CMakeFiles/Makefile2:224: src/usdTri/CMakeFiles/usdTri.dir/all] Error 2
make[1]: Leaving directory '/home/michaelb/dev/USDPluginExamples/build'
make: *** [Makefile:150: all] Error 2
```

**Comment by rlei-weta** [comment]
Hi @mokchira - could definitely reproduce the issue you were seeing.  

Turned out we were missing some critical include & library search directories in the target setup... This issue was masked by the fact that we were always testing against USD installations where the boost & tbb dependencies were bundled!

I have a proposed fix on the [AddUSDIncludeAndLibraryPaths](https://github.com/wetadigital/USDPluginExamples/tree/AddUSDIncludeAndLibraryPaths) branch.  Could you try checking it out and attempting to build - only specifying the USD_ROOT option and relying on system boost & tbb?

Thanks!!

**Comment by mibu138** [comment]
@rlei-weta I checked out the branch and got the following results:
```
michaelb@boswell:~/dev/USDPluginExamples/build$ rm -r *
michaelb@boswell:~/dev/USDPluginExamples/build$ cmake -DUSD_ROOT=$USD ..
-- The CXX compiler identification is GNU 9.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.17", minimum required is "2.7") 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.17", minimum required is "2.7") 
-- Found Boost: /usr/include (found version "1.67.0")  
-- Found Boost: /usr/include (found version "1.67.0") found components: python27 
-- /home/michaelb/dev/USD/build
-- Found USD: /home/michaelb/dev/USD/build/include (found version "0.20.11") 
-- Found TBB: /usr/include (found version "2019.0")  
-- Configuring done
CMake Warning at cmake/USDPluginTools.cmake:278 (add_library):
  Cannot generate a safe runtime search path for target _usdTri because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/michaelb/dev/USD/build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/USDPluginTools.cmake:18 (_usd_library)
  src/usdTri/CMakeLists.txt:1 (usd_shared_library)


CMake Warning at cmake/USDPluginTools.cmake:164 (add_library):
  Cannot generate a safe runtime search path for target usdTri because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/michaelb/dev/USD/build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/USDPluginTools.cmake:18 (_usd_library)
  src/usdTri/CMakeLists.txt:1 (usd_shared_library)


CMake Warning at cmake/USDPluginTools.cmake:164 (add_library):
  Cannot generate a safe runtime search path for target usdTriImaging because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/michaelb/dev/USD/build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/USDPluginTools.cmake:27 (_usd_library)
  src/usdTriImaging/CMakeLists.txt:1 (usd_plugin)


CMake Warning at cmake/USDPluginTools.cmake:164 (add_library):
  Cannot generate a safe runtime search path for target usdTriFileFormat
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/michaelb/dev/USD/build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/USDPluginTools.cmake:27 (_usd_library)
  src/usdTriFileFormat/CMakeLists.txt:1 (usd_plugin)


CMake Warning at cmake/USDPluginTools.cmake:164 (add_library):
  Cannot generate a safe runtime search path for target hdTri because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libtbb.so.2] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/michaelb/dev/USD/build/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  cmake/USDPluginTools.cmake:27 (_usd_library)
  src/hdTri/CMakeLists.txt:3 (usd_plugin)


-- Generating done
-- Build files have been written to: /home/michaelb/dev/USDPluginExamples/build
```

I followed that with a `make` command and was indeed able to build successfully. Cheers!

I'm not sure what to make of the warnings. I don't actually know if my system tbb or boost libs were used or the ones in USD_ROOT. Might need to be tested in a case where I don't have conflicting tbb and boost libraries in USD_ROOT, but since I built USD against those I would imagine I would run into other issues if I just removed them.

**Comment by rlei-weta** [comment]
Hi @mokchira - thanks for the quick test!

> I don't actually know if my system tbb or boost libs were used or the ones in USD_ROOT

If there are boost & tbb includes and libs installed under USD_ROOT, those will be the ones that USD would have built against.  You can check the variables (such as `Boost_INCLUDE_DIR`) in the USD build's CMakeCache.txt:
~/dev/USD/build/build/USD/CMakeCache.txt

> Might need to be tested in a case where I don't have conflicting tbb and boost libraries in USD_ROOT

Yup - those warnings issued are exactly due to tbb and boost under USD_ROOT!  

> but since I built USD against those I would imagine I would run into other issues if I just removed them.

I'd imagine you'll hit runtime issues unless the system boost & tbb are compatible with those installed under USD_ROOT.

Let me know if you find any other issues - cheers for the report!
